using csharp_cartographer_backend._01.Configuration.Enums;
using csharp_cartographer_backend._02.Utilities.Helpers;
using csharp_cartographer_backend._03.Models.Tokens.TokenMaps;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System.Text.Json.Serialization;

namespace csharp_cartographer_backend._03.Models.Tokens
{
    /// <summary>
    ///     A model definition for the NavToken class.
    /// </summary>
    public partial class NavToken
    {
        // Classification constants
        private const string ConstantName = "constant name";
        private const string EventName = "event name";
        private const string FieldName = "field name";
        private const string Identifier = "identifier";
        private const string Keyword = "keyword";
        private const string KeywordControl = "keyword - control";
        private const string KeywordOperator = "keyword - operator";
        private const string LocalName = "local name";
        private const string NamespaceName = "namespace name";
        private const string Operator = "operator";
        private const string ParameterName = "parameter name";
        private const string PropertyName = "property name";

        /// <summary>The unique identifier for a NavToken.</summary>
        public Guid ID { get; set; }

        /// <summary>The index value for the token in the list of NavTokens.</summary>
        public int Index { get; set; }

        /// <summary>The token text.</summary>
        public string Text { get; set; }

        /// <summary>The token classification set. </summary>
        public Classifications Classifications { get; set; }

        /// <summary>The color the token will be highlighted in the UI.</summary>
        public string? HighlightColor { get; set; }

        /// <summary>A list of the tokens leading trivia strings.</summary>
        public IEnumerable<string> LeadingTrivia { get; set; }

        /// <summary>A list of the tokens trailing trivia strings.</summary>
        public IEnumerable<string> TrailingTrivia { get; set; }

        /// <summary>A collection of token semantic data to display in the UI.</summary>
        public SemanticMap Map { get; set; }

        /// <summary>A list of ancestor nodes & data attached to the token.</summary>
        public IEnumerable<TokenChart> Charts { get; set; } = [];

        /// <summary>The Roslyn SyntaxKind of the token.</summary>
        [JsonIgnore]
        public SyntaxKind Kind { get; set; }

        /// <summary>The general syntax category of the token.</summary>
        [JsonIgnore]
        public PrimaryKind PrimaryKind { get; set; } = PrimaryKind.Unknown;

        /// <summary>The primary role of the token in its given context.</summary>
        [JsonIgnore]
        public SemanticRole SemanticRole { get; set; } = SemanticRole.Unknown;

        /// <summary>The focused role of the token in its given context.</summary>
        [JsonIgnore]
        public FocusedRole FocusedRole { get; set; } = FocusedRole.Unknown;

        /// <summary>The TextSpan of the token text.</summary>
        [JsonIgnore]
        public TextSpan Span { get; set; }

        /// <summary>The Roslyn generated SyntaxToken.</summary>
        [JsonIgnore]
        public SyntaxToken RoslynToken { get; set; }

        /// <summary>The token that comes before this one sequentially.</summary>
        [JsonIgnore]
        public NavToken? PrevToken { get; set; }

        /// <summary>The token that comes after this one sequentially.</summary>
        [JsonIgnore]
        public NavToken? NextToken { get; set; }

        /// <summary>The SyntaxKind(s) of the token's ancestor nodes.</summary>
        [JsonIgnore]
        public AncestorNodeKinds Ancestors { get; set; }

        /// <summary>The token's semantic data.</summary>
        [JsonIgnore]
        public TokenSemanticData? SemanticData { get; set; }

        public NavToken()
        {
        }

        /// <summary>Constructor for the NavToken model.</summary>
        /// <param name="roslynToken">The SyntaxToken generated by the Roslyn code analysis library.</param>
        /// <param name="index">The index of the token in the list.</param>
        public NavToken(SyntaxToken roslynToken, int index)
        {
            ID = Guid.NewGuid();
            Index = index;
            Text = roslynToken.Text;
            Kind = roslynToken.Kind();
            LeadingTrivia = TriviaHelper.GetLeadingTrivia(roslynToken);
            TrailingTrivia = TriviaHelper.GetTrailingTrivia(roslynToken);
            Span = roslynToken.Span;
            RoslynToken = roslynToken;
            Ancestors = new AncestorNodeKinds(roslynToken);
        }
    }
}
