<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<!--<LangVersion>11</LangVersion>-->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>csharp_cartographer_backend</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Focused\delimiter-focused-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Focused\identifier-focused-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Focused\keyword-focused-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Focused\keyword-operator-focused-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Focused\literal-focused-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Focused\operator-focused-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\delimiter-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\identifier-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\keyword-operator-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\keyword-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\literal-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\misc-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\operator-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\Definitions\Roles\punctuation-role-definitions.json" />
    <Content Remove="01.Configuration\EmbeddedJson\demo-options.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Focused\delimiter-focused-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Focused\identifier-focused-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Focused\keyword-focused-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Focused\keyword-operator-focused-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Focused\literal-focused-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Focused\operator-focused-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\modifier-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\semantic-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\delimiter-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\identifier-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\keyword-operator-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\keyword-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\literal-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\misc-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\operator-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\Definitions\Roles\punctuation-role-definitions.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\demo-options.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\DemoInsights\controller-insights.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\DemoInsights\dto-insights.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\DemoInsights\helper-insights.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\DemoInsights\model-insights.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\DemoInsights\client-insights.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\DemoInsights\service-insights.json" />
    <EmbeddedResource Include="01.Configuration\EmbeddedJson\DemoInsights\workflow-insights.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.0.1" />
  </ItemGroup>

</Project>
