using csharp_cartographer_backend._03.Models.Tokens;
using csharp_cartographer_backend._05.Services.Roslyn;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Classification;
using Microsoft.CodeAnalysis.Text;

namespace csharp_cartographer_backend._05.Services.Tokens
{
    public class NavTokenGenerator : INavTokenGenerator
    {
        private readonly IRoslynAnalyzer _roslynAnalyzer;

        public NavTokenGenerator(IRoslynAnalyzer roslynAnalyzer)
        {
            _roslynAnalyzer = roslynAnalyzer;
        }

        /// <summary>
        /// Turns the source code into a list of SyntaxTokens generated by Roslyn.
        /// Then iterates through that list to create a list of NavTokens
        /// </summary>
        /// <param name="semanticModel">The Roslyn generated semantic model.</param>
        /// <param name="syntaxTree">The Roslyn generated syntax tree.</param>
        /// <param name="document">The Roslyn generated document.</param>
        /// <returns>A list of NavTokens.</returns>
        public async Task<List<NavToken>> GenerateNavTokens(SemanticModel semanticModel, SyntaxTree syntaxTree, Document document)
        {
            List<NavToken> navTokens = [];

            SyntaxNode root = syntaxTree.GetRoot();
            var roslynTokens = root.DescendantTokens();
            var classificationLookup = await BuildClassificationLookup(syntaxTree, document);

            int index = 0;
            foreach (var token in roslynTokens)
            {
                var classification = GetTokenClassification(token, classificationLookup);
                var newToken = new NavToken(token, semanticModel, syntaxTree, index, classification);

                _roslynAnalyzer.AddTokenSemanticData(newToken, semanticModel, syntaxTree);

                navTokens.Add(newToken);

                // each token in list needs data from the ones before & after for syntax highlighting
                if (index > 0)
                {
                    var prevToken = navTokens[index - 1];

                    newToken.PrevToken = prevToken;
                    prevToken.NextToken = newToken;
                }
                index++;
            }

            return navTokens;
        }

        private static async Task<IReadOnlyDictionary<int, List<ClassifiedSpan>>> BuildClassificationLookup(SyntaxTree syntaxTree, Document document)
        {
            var classifiedSpans = await GetClassifiedSpans(syntaxTree, document);
            return classifiedSpans
                .GroupBy(c => c.TextSpan.Start)
                .ToDictionary(g => g.Key, g => g.ToList());
        }

        private static string? GetTokenClassification(SyntaxToken token, IReadOnlyDictionary<int, List<ClassifiedSpan>> classificationLookup)
        {
            if (!classificationLookup.TryGetValue(token.Span.Start, out var candidates) || candidates is null)
            {
                return null;
            }
            return candidates.FirstOrDefault(c => c.TextSpan.Length == token.Span.Length).ClassificationType;
        }

        private static async Task<IEnumerable<ClassifiedSpan>> GetClassifiedSpans(SyntaxTree syntaxTree, Document document)
        {
            var text = await syntaxTree.GetTextAsync();
            var fullSpan = new TextSpan(0, text.Length);
            return await Classifier.GetClassifiedSpansAsync(document, fullSpan) ?? [];
        }
    }
}
