namespace csharp_cartographer_backend._01.Configuration.Enums
{
    public enum RoslynKind
    {
        Argument,
        Attribute,
        BaseList,
        ClassDeclaration,
        ConstructorDeclaration,
        FieldDeclaration,
        ForEachStatement,
        ForStatement,
        GenericName,
        IdentifierName,
        InterfaceDeclaration,
        InvocationExpression,
        LocalDeclarationStatement,
        MethodDeclaration,
        NameColon,
        NullableType,
        Parameter,
        PropertyDeclaration,
        QualifiedName,
        RecordDeclaration,
        SimpleBaseType,
        TypeArgumentList,
        TypeParameterList,
        TypeParameterConstraintClause,
        UsingDirective,
        VariableDeclaration,
        VariableDeclarator,
    }
}
